#!/usr/bin/env python3
"""
Gera stubs dos diálogos de seleção, para o SPIKE de compilar o domínio para Android.

ISTO NÃO É O DESENHO FINAL. Deixe isso claro antes de qualquer coisa.

O desenho final é a abstração de solicitação/resposta de DEC-003 e DEC-026: o domínio emite
um pedido de escolha, a camada de apresentação resolve. Esses stubs são um ATALHO com
propósito único e prazo curto — responder, em horas em vez de semanas, a pergunta:

    carregar um .chum5 no Android toca algum diálogo?

A hipótese é que não. Carregar é parser XML e construção de objetos; os diálogos aparecem ao
CRIAR e MODIFICAR coisas que exigem escolha do usuário. Se a hipótese estiver certa, dá para
ter um APK que abre uma ficha muito antes de a abstração de seleção estar pronta — e cada
stub que for chamado em tempo de execução lança, apontando exatamente o que falta abstrair.

Por que gerar em vez de escrever à mão: as assinaturas são extraídas dos formulários REAIS
em Chummer/Forms/. Escrever 26 classes e 57 membros à mão é onde se erra o tipo de retorno e
se descobre no CI cinco minutos depois.

Saída: src/Chummer.Compat/DialogStubs.g.cs

O diretório src/Chummer.Compat/ é deliberado: o projeto legado compila `src/Chummer.Core/**`
(DEC-013), então qualquer coisa fora dessa pasta é automaticamente invisível para ele. Sem
isso, os stubs colidiriam com os tipos WinForms de verdade no build net48.
"""

import os
import re
import sys
import collections

RAIZ = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BACKEND = os.path.join(RAIZ, 'Chummer', 'Backend')
FORMS = os.path.join(RAIZ, 'Chummer', 'Forms')
SAIDA = os.path.join(RAIZ, 'src', 'Chummer.Compat', 'DialogStubs.g.cs')

RE_USO = re.compile(r'ThreadSafeForm<([A-Za-z0-9_]+)>')
RE_MEMBRO_USADO = re.compile(r'\.MyForm\.([A-Za-z0-9_]+)')


def arquivos(raiz, ext='.cs'):
    for dir_, _, nomes in os.walk(raiz):
        if '/obj/' in dir_ or '/bin/' in dir_:
            continue
        for n in nomes:
            if n.endswith(ext):
                yield os.path.join(dir_, n)


def ler(p):
    with open(p, encoding='utf-8-sig', errors='replace') as f:
        return f.read()


def levantar_uso():
    """Quais diálogos o domínio usa, e quais membros de cada um."""
    tipos, membros = set(), set()
    for p in arquivos(BACKEND):
        t = ler(p)
        tipos.update(RE_USO.findall(t))
        membros.update(RE_MEMBRO_USADO.findall(t))
    return tipos, membros


def assinaturas_reais(tipos, membros):
    """Extrai as assinaturas verdadeiras dos formulários em Chummer/Forms/.

    Só os membros que o domínio realmente chama entram no stub. Copiar a classe inteira
    arrastaria a implementação WinForms junto, que é justamente o que se quer evitar.
    """
    achado = collections.defaultdict(dict)
    for p in arquivos(FORMS):
        t = ler(p)
        for tipo in tipos:
            if not re.search(rf'\bclass\s+{tipo}\b', t):
                continue
            for m in membros:
                # propriedade ou método público, capturando o tipo de retorno
                pat = re.compile(
                    rf'^\s*public\s+(?!class|struct)([\w<>,\[\]\?\. ]+?)\s+{m}\s*(\(|\{{|=>|$)',
                    re.M)
                mm = pat.search(t)
                if mm and m not in achado[tipo]:
                    retorno = mm.group(1).strip()
                    ehmetodo = mm.group(2) == '('
                    achado[tipo][m] = (retorno, ehmetodo)
    return achado


def valor_padrao(tipo):
    t = tipo.replace('?', '').strip()
    if t in ('void',):
        return None
    if t in ('string',):
        return '""'
    if t in ('bool',):
        return 'false'
    if t in ('int', 'decimal', 'double', 'float', 'long', 'short', 'byte'):
        return '0'
    return 'default'


def emitir(achado, tipos):
    L = []
    L.append('// <auto-generated />')
    L.append('// GERADO por scripts/gerar-stubs-dialogos.py — não edite à mão.')
    L.append('//')
    L.append('// SPIKE, não desenho final. Ver o cabeçalho do gerador e DEC-037.')
    L.append('//')
    L.append('// Cada membro lança NotSupportedException. Isso é intencional: se carregar um')
    L.append('// .chum5 no Android atingir um destes, a exceção diz exatamente qual diálogo')
    L.append('// precisa ser abstraído de verdade — que é a informação que este spike existe')
    L.append('// para produzir.')
    L.append('')
    L.append('using System;')
    L.append('using System.Threading;')
    L.append('using System.Threading.Tasks;')
    L.append('')
    L.append('namespace Chummer')
    L.append('{')
    L.append('    /// <summary>Substituto de System.Windows.Forms.DialogResult.</summary>')
    L.append('    public enum DialogResult')
    L.append('    {')
    L.append('        None = 0, OK = 1, Cancel = 2, Abort = 3,')
    L.append('        Retry = 4, Ignore = 5, Yes = 6, No = 7')
    L.append('    }')
    L.append('')
    L.append('    /// <summary>')
    L.append('    /// Substituto de ThreadSafeForm&lt;T&gt;. A afinidade de thread do WinForms não')
    L.append('    /// existe no destino, então não há nada a proteger — sobra a forma da API.')
    L.append('    /// </summary>')
    L.append('    public sealed class ThreadSafeForm<T> : IDisposable where T : class, new()')
    L.append('    {')
    L.append('        public T MyForm { get; private set; }')
    L.append('')
    L.append('        private ThreadSafeForm(T objForm) { MyForm = objForm; }')
    L.append('')
    L.append('        public static ThreadSafeForm<T> Get(Func<T> funcCreator)')
    L.append('            => new ThreadSafeForm<T>(funcCreator());')
    L.append('')
    L.append('        public static Task<ThreadSafeForm<T>> GetAsync(Func<T> funcCreator,')
    L.append('            CancellationToken token = default)')
    L.append('            => Task.FromResult(new ThreadSafeForm<T>(funcCreator()));')
    L.append('')
    L.append('        public DialogResult ShowDialogSafe(object objParent = null,')
    L.append('            CancellationToken token = default)')
    L.append('            => throw new NotSupportedException(')
    L.append('                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);')
    L.append('')
    L.append('        public Task<DialogResult> ShowDialogSafeAsync(object objParent = null,')
    L.append('            CancellationToken token = default)')
    L.append('            => throw new NotSupportedException(')
    L.append('                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);')
    L.append('')
    L.append('        public void Dispose() { }')
    L.append('    }')
    L.append('')

    for tipo in sorted(tipos):
        membros = achado.get(tipo, {})
        L.append(f'    /// <summary>Stub de {tipo}. Membros usados pelo domínio: {len(membros)}.</summary>')
        L.append(f'    public sealed class {tipo}')
        L.append('    {')
        for nome in sorted(membros):
            retorno, ehmetodo = membros[nome]
            lanca = (f'throw new NotSupportedException("{tipo}.{nome} não abstraído");')
            if ehmetodo:
                L.append(f'        public {retorno} {nome}(params object[] args) => {lanca}')
            elif retorno == 'void':
                continue
            else:
                L.append(f'        public {retorno} {nome}')
                L.append('        {')
                L.append(f'            get => {lanca}')
                L.append(f'            set => {lanca}')
                L.append('        }')
        L.append('    }')
        L.append('')

    L.append('}')
    return '\n'.join(L) + '\n'


def main():
    tipos, membros = levantar_uso()
    achado = assinaturas_reais(tipos, membros)

    # Um diálogo usado só via ShowDialogSafe, sem nenhum .MyForm.X, não tem membro a
    # descobrir — mas o tipo precisa existir mesmo assim, senão ThreadSafeForm<X> não
    # compila. A primeira versão omitia esses quatro e o stub não fechava.
    sem_assinatura = sorted(t for t in tipos if t not in achado)
    print(f'diálogos usados pelo domínio: {len(tipos)}')
    print(f'membros distintos chamados via .MyForm.: {len(membros)}')
    print(f'diálogos com assinatura encontrada em Chummer/Forms/: {len(achado)}')
    if sem_assinatura:
        print(f'SEM assinatura encontrada ({len(sem_assinatura)}): {", ".join(sem_assinatura)}')

    os.makedirs(os.path.dirname(SAIDA), exist_ok=True)
    with open(SAIDA, 'w', encoding='utf-8') as f:
        f.write(emitir(achado, tipos))
    total = sum(len(v) for v in achado.values())
    print(f'\ngerado: {os.path.relpath(SAIDA, RAIZ)}  ({len(achado)} classes, {total} membros)')


if __name__ == '__main__':
    sys.exit(main())
