// <auto-generated />
// GERADO por scripts/gerar-stubs-dialogos.py — não edite à mão.
//
// SPIKE, não desenho final. Ver o cabeçalho do gerador e DEC-037.
//
// Cada membro lança NotSupportedException. Isso é intencional: se carregar um
// .chum5 no Android atingir um destes, a exceção diz exatamente qual diálogo
// precisa ser abstraído de verdade — que é a informação que este spike existe
// para produzir.

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Drawing;
using System.Xml;
using Chummer.Backend.Equipment;

namespace Chummer
{
    /// <summary>Substituto de System.Windows.Forms.DialogResult.</summary>
    public enum DialogResult
    {
        None = 0, OK = 1, Cancel = 2, Abort = 3,
        Retry = 4, Ignore = 5, Yes = 6, No = 7
    }

    /// <summary>
    /// Superfície que os diálogos herdam de Form/Control e que o domínio usa.
    /// Não é reimplementação: só o suficiente para vincular, lançando se chamado.
    /// </summary>
    public abstract class DialogStubBase : IDisposable
    {
        public double Opacity
        {
            get => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
            set => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
        }

        public string Text
        {
            get => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
            set => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
        }

        public object Tag
        {
            get => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
            set => throw new NotSupportedException("Diálogo não abstraído: " + GetType().Name);
        }

        public virtual void Dispose() { }
    }

    /// <summary>
    /// Espelha as extensões DoThreadSafe* de WinFormsExtensions, que o domínio chama
    /// sobre o formulário. Sem afinidade de thread não há o que proteger; lançam porque
    /// chegar aqui significa que um diálogo real foi tocado.
    /// </summary>
    public static class DialogStubExtensions
    {
        public static void DoThreadSafe<T>(this T objForm, Action<T> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static void DoThreadSafe<T>(this T objForm, Action<T, CancellationToken> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static Task DoThreadSafeAsync<T>(this T objForm, Action<T> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static Task DoThreadSafeAsync<T>(this T objForm, Action<T, CancellationToken> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static TResult DoThreadSafeFunc<T, TResult>(this T objForm, Func<T, TResult> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static TResult DoThreadSafeFunc<T, TResult>(this T objForm, Func<T, CancellationToken, TResult> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static Task<TResult> DoThreadSafeFuncAsync<T, TResult>(this T objForm, Func<T, TResult> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public static Task<TResult> DoThreadSafeFuncAsync<T, TResult>(this T objForm, Func<T, CancellationToken, TResult> funcToRun,
            CancellationToken token = default) where T : DialogStubBase
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

    }

    /// <summary>
    /// Substituto de ThreadSafeForm&lt;T&gt;. A afinidade de thread do WinForms não
    /// existe no destino, então não há nada a proteger — sobra a forma da API.
    /// </summary>
    public sealed class ThreadSafeForm<T> : IDisposable where T : DialogStubBase, new()
    {
        public T MyForm { get; private set; }

        private ThreadSafeForm(T objForm) { MyForm = objForm; }

        public static ThreadSafeForm<T> Get(Func<T> funcCreator)
            => new ThreadSafeForm<T>(funcCreator());

        public static Task<ThreadSafeForm<T>> GetAsync(Func<T> funcCreator,
            CancellationToken token = default)
            => Task.FromResult(new ThreadSafeForm<T>(funcCreator()));

        public static Task<ThreadSafeForm<T>> GetAsync(Func<CancellationToken, T> funcCreator,
            CancellationToken token = default)
            => Task.FromResult(new ThreadSafeForm<T>(funcCreator(token)));

        public static Task<ThreadSafeForm<T>> GetCoreAsync(bool blnSync, Func<T> funcCreator,
            CancellationToken token = default)
            => Task.FromResult(new ThreadSafeForm<T>(funcCreator()));

        public Task<DialogResult> ShowDialogSafeCoreAsync(bool blnSync, object objParent = null,
            CancellationToken token = default)
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public DialogResult ShowDialogSafe(object objParent = null,
            CancellationToken token = default)
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public Task<DialogResult> ShowDialogSafeAsync(object objParent = null,
            CancellationToken token = default)
            => throw new NotSupportedException(
                "Diálogo de seleção ainda não abstraído: " + typeof(T).Name);

        public void Dispose() { }
    }

    /// <summary>Stub de LoadingBar. Barra de progresso: no-op, nunca lança.</summary>
    public sealed class LoadingBar : DialogStubBase
    {
        public enum ProgressBarTextPatterns
        {
            Saving = 0, Loading = 1, Initializing = 2, Scanning = 3, Printing = 4
        }

        public string CharacterFile { get; set; } = string.Empty;

        public Task SetCharacterFileAsync(string value, CancellationToken token = default)
        {
            CharacterFile = value;
            return Task.CompletedTask;
        }

        public void Reset(int intMaxProgressBarValue = 100) { }

        public Task ResetAsync(int intMaxProgressBarValue = 100,
            CancellationToken token = default) => Task.CompletedTask;

        public void PerformStep(string strStepName = "",
            ProgressBarTextPatterns eUseTextPattern = ProgressBarTextPatterns.Loading) { }

        public Task PerformStepAsync(string strStepName = "",
            ProgressBarTextPatterns eUseTextPattern = ProgressBarTextPatterns.Loading,
            CancellationToken token = default) => Task.CompletedTask;
    }

    /// <summary>Stub de EditGlobalSettings. Membros usados pelo domínio: 2.</summary>
    public sealed class EditGlobalSettings : DialogStubBase
    {
        public EditGlobalSettings() { }
        public EditGlobalSettings(params object[] args) { }
        public async Task DoLinkPdf(params object[] args) => throw new NotSupportedException("EditGlobalSettings.DoLinkPdf não abstraído");
        public Task DoLinkPdfReader(params object[] args) => throw new NotSupportedException("EditGlobalSettings.DoLinkPdfReader não abstraído");
    }

    /// <summary>Stub de EditNotes. Membros usados pelo domínio: 2.</summary>
    public sealed class EditNotes : DialogStubBase
    {
        public EditNotes() { }
        public EditNotes(params object[] args) { }
        public string Notes
        {
            get => throw new NotSupportedException("EditNotes.Notes não abstraído");
            set => throw new NotSupportedException("EditNotes.Notes não abstraído");
        }
        public Color NotesColor
        {
            get => throw new NotSupportedException("EditNotes.NotesColor não abstraído");
            set => throw new NotSupportedException("EditNotes.NotesColor não abstraído");
        }
    }

    /// <summary>Stub de ReloadWeapon. Membros usados pelo domínio: 4.</summary>
    public sealed class ReloadWeapon : DialogStubBase
    {
        public ReloadWeapon() { }
        public ReloadWeapon(params object[] args) { }
        public IEnumerable<Gear> Ammo
        {
            get => throw new NotSupportedException("ReloadWeapon.Ammo não abstraído");
            set => throw new NotSupportedException("ReloadWeapon.Ammo não abstraído");
        }
        public IEnumerable<string> Count
        {
            get => throw new NotSupportedException("ReloadWeapon.Count não abstraído");
            set => throw new NotSupportedException("ReloadWeapon.Count não abstraído");
        }
        public async Task<string> GetSelectedAmmoAsync(params object[] args) => throw new NotSupportedException("ReloadWeapon.GetSelectedAmmoAsync não abstraído");
        public async Task<decimal> GetSelectedCountAsync(params object[] args) => throw new NotSupportedException("ReloadWeapon.GetSelectedCountAsync não abstraído");
    }

    /// <summary>Stub de SelectAIProgram. Membros usados pelo domínio: 2.</summary>
    public sealed class SelectAIProgram : DialogStubBase
    {
        public SelectAIProgram() { }
        public SelectAIProgram(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectAIProgram.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectAIProgram.AddAgain não abstraído");
        }
        public string SelectedProgram
        {
            get => throw new NotSupportedException("SelectAIProgram.SelectedProgram não abstraído");
            set => throw new NotSupportedException("SelectAIProgram.SelectedProgram não abstraído");
        }
    }

    /// <summary>Stub de SelectArmorMod. Membros usados pelo domínio: 4.</summary>
    public sealed class SelectArmorMod : DialogStubBase
    {
        public SelectArmorMod() { }
        public SelectArmorMod(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectArmorMod.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectArmorMod.AddAgain não abstraído");
        }
        public string AllowedCategories
        {
            get => throw new NotSupportedException("SelectArmorMod.AllowedCategories não abstraído");
            set => throw new NotSupportedException("SelectArmorMod.AllowedCategories não abstraído");
        }
        public bool ExcludeGeneralCategory
        {
            get => throw new NotSupportedException("SelectArmorMod.ExcludeGeneralCategory não abstraído");
            set => throw new NotSupportedException("SelectArmorMod.ExcludeGeneralCategory não abstraído");
        }
        public string SelectedArmorMod
        {
            get => throw new NotSupportedException("SelectArmorMod.SelectedArmorMod não abstraído");
            set => throw new NotSupportedException("SelectArmorMod.SelectedArmorMod não abstraído");
        }
    }

    /// <summary>Stub de SelectArt. Membros usados pelo domínio: 1.</summary>
    public sealed class SelectArt : DialogStubBase
    {
        public SelectArt() { }
        public enum Mode { Art, Enhancement, Enchantment, Ritual }
        public SelectArt(params object[] args) { }
        public string SelectedItem
        {
            get => throw new NotSupportedException("SelectArt.SelectedItem não abstraído");
            set => throw new NotSupportedException("SelectArt.SelectedItem não abstraído");
        }
    }

    /// <summary>Stub de SelectAttribute. Membros usados pelo domínio: 2.</summary>
    public sealed class SelectAttribute : DialogStubBase
    {
        public SelectAttribute() { }
        public SelectAttribute(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectAttribute.Description não abstraído");
            set => throw new NotSupportedException("SelectAttribute.Description não abstraído");
        }
        public string SelectedAttribute
        {
            get => throw new NotSupportedException("SelectAttribute.SelectedAttribute não abstraído");
            set => throw new NotSupportedException("SelectAttribute.SelectedAttribute não abstraído");
        }
    }

    /// <summary>Stub de SelectBuildMethod. Membros usados pelo domínio: 0.</summary>
    public sealed class SelectBuildMethod : DialogStubBase
    {
        public SelectBuildMethod() { }
        public SelectBuildMethod(params object[] args) { }
    }

    /// <summary>Stub de SelectComplexForm. Membros usados pelo domínio: 2.</summary>
    public sealed class SelectComplexForm : DialogStubBase
    {
        public SelectComplexForm() { }
        public SelectComplexForm(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectComplexForm.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectComplexForm.AddAgain não abstraído");
        }
        public string SelectedComplexForm
        {
            get => throw new NotSupportedException("SelectComplexForm.SelectedComplexForm não abstraído");
            set => throw new NotSupportedException("SelectComplexForm.SelectedComplexForm não abstraído");
        }
    }

    /// <summary>Stub de SelectDiceHits. Membros usados pelo domínio: 3.</summary>
    public sealed class SelectDiceHits : DialogStubBase
    {
        public SelectDiceHits() { }
        public SelectDiceHits(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectDiceHits.Description não abstraído");
            set => throw new NotSupportedException("SelectDiceHits.Description não abstraído");
        }
        public int Result
        {
            get => throw new NotSupportedException("SelectDiceHits.Result não abstraído");
            set => throw new NotSupportedException("SelectDiceHits.Result não abstraído");
        }
        public async Task SetDiceAsync(params object[] args) => throw new NotSupportedException("SelectDiceHits.SetDiceAsync não abstraído");
    }

    /// <summary>Stub de SelectItem. Membros usados pelo domínio: 8.</summary>
    public sealed class SelectItem : DialogStubBase
    {
        public SelectItem() { }
        public SelectItem(params object[] args) { }
        public bool AllowAutoSelect
        {
            get => throw new NotSupportedException("SelectItem.AllowAutoSelect não abstraído");
            set => throw new NotSupportedException("SelectItem.AllowAutoSelect não abstraído");
        }
        public string Description
        {
            get => throw new NotSupportedException("SelectItem.Description não abstraído");
            set => throw new NotSupportedException("SelectItem.Description não abstraído");
        }
        public void ForceItem(params object[] args) => throw new NotSupportedException("SelectItem.ForceItem não abstraído");
        public string SelectedItem
        {
            get => throw new NotSupportedException("SelectItem.SelectedItem não abstraído");
            set => throw new NotSupportedException("SelectItem.SelectedItem não abstraído");
        }
        public string SelectedName
        {
            get => throw new NotSupportedException("SelectItem.SelectedName não abstraído");
            set => throw new NotSupportedException("SelectItem.SelectedName não abstraído");
        }
        public void SetDropdownItemsMode(params object[] args) => throw new NotSupportedException("SelectItem.SetDropdownItemsMode não abstraído");
        public void SetGeneralItemsMode(params object[] args) => throw new NotSupportedException("SelectItem.SetGeneralItemsMode não abstraído");
        public void SetRestrictedMode(params object[] args) => throw new NotSupportedException("SelectItem.SetRestrictedMode não abstraído");
    }

    /// <summary>Stub de SelectLimit. Membros usados pelo domínio: 3.</summary>
    public sealed class SelectLimit : DialogStubBase
    {
        public SelectLimit() { }
        public SelectLimit(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectLimit.Description não abstraído");
            set => throw new NotSupportedException("SelectLimit.Description não abstraído");
        }
        public string SelectedDisplayLimit
        {
            get => throw new NotSupportedException("SelectLimit.SelectedDisplayLimit não abstraído");
            set => throw new NotSupportedException("SelectLimit.SelectedDisplayLimit não abstraído");
        }
        public string SelectedLimit
        {
            get => throw new NotSupportedException("SelectLimit.SelectedLimit não abstraído");
            set => throw new NotSupportedException("SelectLimit.SelectedLimit não abstraído");
        }
    }

    /// <summary>Stub de SelectMartialArt. Membros usados pelo domínio: 2.</summary>
    public sealed class SelectMartialArt : DialogStubBase
    {
        public SelectMartialArt() { }
        public SelectMartialArt(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectMartialArt.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectMartialArt.AddAgain não abstraído");
        }
        public string SelectedMartialArt
        {
            get => throw new NotSupportedException("SelectMartialArt.SelectedMartialArt não abstraído");
            set => throw new NotSupportedException("SelectMartialArt.SelectedMartialArt não abstraído");
        }
    }

    /// <summary>Stub de SelectMentorSpirit. Membros usados pelo domínio: 4.</summary>
    public sealed class SelectMentorSpirit : DialogStubBase
    {
        public SelectMentorSpirit() { }
        public SelectMentorSpirit(params object[] args) { }
        public string Choice1
        {
            get => throw new NotSupportedException("SelectMentorSpirit.Choice1 não abstraído");
            set => throw new NotSupportedException("SelectMentorSpirit.Choice1 não abstraído");
        }
        public string Choice2
        {
            get => throw new NotSupportedException("SelectMentorSpirit.Choice2 não abstraído");
            set => throw new NotSupportedException("SelectMentorSpirit.Choice2 não abstraído");
        }
        public string ForcedMentor
        {
            get => throw new NotSupportedException("SelectMentorSpirit.ForcedMentor não abstraído");
            set => throw new NotSupportedException("SelectMentorSpirit.ForcedMentor não abstraído");
        }
        public string SelectedMentor
        {
            get => throw new NotSupportedException("SelectMentorSpirit.SelectedMentor não abstraído");
            set => throw new NotSupportedException("SelectMentorSpirit.SelectedMentor não abstraído");
        }
    }

    /// <summary>Stub de SelectMetamagic. Membros usados pelo domínio: 1.</summary>
    public sealed class SelectMetamagic : DialogStubBase
    {
        public SelectMetamagic() { }
        public SelectMetamagic(params object[] args) { }
        public string SelectedMetamagic
        {
            get => throw new NotSupportedException("SelectMetamagic.SelectedMetamagic não abstraído");
            set => throw new NotSupportedException("SelectMetamagic.SelectedMetamagic não abstraído");
        }
    }

    /// <summary>Stub de SelectMetatypeKarma. Membros usados pelo domínio: 0.</summary>
    public sealed class SelectMetatypeKarma : DialogStubBase
    {
        public SelectMetatypeKarma() { }
        public SelectMetatypeKarma(params object[] args) { }
    }

    /// <summary>Stub de SelectMetatypePriority. Membros usados pelo domínio: 0.</summary>
    public sealed class SelectMetatypePriority : DialogStubBase
    {
        public SelectMetatypePriority() { }
        public SelectMetatypePriority(params object[] args) { }
    }

    /// <summary>Stub de SelectNumber. Membros usados pelo domínio: 5.</summary>
    public sealed class SelectNumber : DialogStubBase
    {
        public SelectNumber() { }
        public SelectNumber(params object[] args) { }
        public bool AllowCancel
        {
            get => throw new NotSupportedException("SelectNumber.AllowCancel não abstraído");
            set => throw new NotSupportedException("SelectNumber.AllowCancel não abstraído");
        }
        public string Description
        {
            get => throw new NotSupportedException("SelectNumber.Description não abstraído");
            set => throw new NotSupportedException("SelectNumber.Description não abstraído");
        }
        public decimal Maximum
        {
            get => throw new NotSupportedException("SelectNumber.Maximum não abstraído");
            set => throw new NotSupportedException("SelectNumber.Maximum não abstraído");
        }
        public decimal Minimum
        {
            get => throw new NotSupportedException("SelectNumber.Minimum não abstraído");
            set => throw new NotSupportedException("SelectNumber.Minimum não abstraído");
        }
        public decimal SelectedValue
        {
            get => throw new NotSupportedException("SelectNumber.SelectedValue não abstraído");
            set => throw new NotSupportedException("SelectNumber.SelectedValue não abstraído");
        }
    }

    /// <summary>Stub de SelectOptionalPower. Membros usados pelo domínio: 3.</summary>
    public sealed class SelectOptionalPower : DialogStubBase
    {
        public SelectOptionalPower() { }
        public SelectOptionalPower(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectOptionalPower.Description não abstraído");
            set => throw new NotSupportedException("SelectOptionalPower.Description não abstraído");
        }
        public string SelectedPower
        {
            get => throw new NotSupportedException("SelectOptionalPower.SelectedPower não abstraído");
            set => throw new NotSupportedException("SelectOptionalPower.SelectedPower não abstraído");
        }
        public string SelectedPowerExtra
        {
            get => throw new NotSupportedException("SelectOptionalPower.SelectedPowerExtra não abstraído");
            set => throw new NotSupportedException("SelectOptionalPower.SelectedPowerExtra não abstraído");
        }
    }

    /// <summary>Stub de SelectPower. Membros usados pelo domínio: 7.</summary>
    public sealed class SelectPower : DialogStubBase
    {
        public SelectPower() { }
        public SelectPower(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectPower.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectPower.AddAgain não abstraído");
        }
        public bool ForBonus
        {
            get => throw new NotSupportedException("SelectPower.ForBonus não abstraído");
            set => throw new NotSupportedException("SelectPower.ForBonus não abstraído");
        }
        public bool IgnoreLimits
        {
            get => throw new NotSupportedException("SelectPower.IgnoreLimits não abstraído");
            set => throw new NotSupportedException("SelectPower.IgnoreLimits não abstraído");
        }
        public string LimitToPowers
        {
            get => throw new NotSupportedException("SelectPower.LimitToPowers não abstraído");
            set => throw new NotSupportedException("SelectPower.LimitToPowers não abstraído");
        }
        public int LimitToRating
        {
            get => throw new NotSupportedException("SelectPower.LimitToRating não abstraído");
            set => throw new NotSupportedException("SelectPower.LimitToRating não abstraído");
        }
        public decimal PointsPerLevel
        {
            get => throw new NotSupportedException("SelectPower.PointsPerLevel não abstraído");
            set => throw new NotSupportedException("SelectPower.PointsPerLevel não abstraído");
        }
        public string SelectedPower
        {
            get => throw new NotSupportedException("SelectPower.SelectedPower não abstraído");
            set => throw new NotSupportedException("SelectPower.SelectedPower não abstraído");
        }
    }

    /// <summary>Stub de SelectSide. Membros usados pelo domínio: 3.</summary>
    public sealed class SelectSide : DialogStubBase
    {
        public SelectSide() { }
        public SelectSide(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectSide.Description não abstraído");
            set => throw new NotSupportedException("SelectSide.Description não abstraído");
        }
        public void ForceValue(params object[] args) => throw new NotSupportedException("SelectSide.ForceValue não abstraído");
        public string SelectedSide
        {
            get => throw new NotSupportedException("SelectSide.SelectedSide não abstraído");
            set => throw new NotSupportedException("SelectSide.SelectedSide não abstraído");
        }
    }

    /// <summary>Stub de SelectSkill. Membros usados pelo domínio: 12.</summary>
    public sealed class SelectSkill : DialogStubBase
    {
        public SelectSkill() { }
        public SelectSkill(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectSkill.Description não abstraído");
            set => throw new NotSupportedException("SelectSkill.Description não abstraído");
        }
        public string ExcludeCategory
        {
            get => throw new NotSupportedException("SelectSkill.ExcludeCategory não abstraído");
            set => throw new NotSupportedException("SelectSkill.ExcludeCategory não abstraído");
        }
        public string ExcludeSkill
        {
            get => throw new NotSupportedException("SelectSkill.ExcludeSkill não abstraído");
            set => throw new NotSupportedException("SelectSkill.ExcludeSkill não abstraído");
        }
        public string ExcludeSkillGroup
        {
            get => throw new NotSupportedException("SelectSkill.ExcludeSkillGroup não abstraído");
            set => throw new NotSupportedException("SelectSkill.ExcludeSkillGroup não abstraído");
        }
        public XmlNode LimitToCategories
        {
            get => throw new NotSupportedException("SelectSkill.LimitToCategories não abstraído");
            set => throw new NotSupportedException("SelectSkill.LimitToCategories não abstraído");
        }
        public string LimitToSkill
        {
            get => throw new NotSupportedException("SelectSkill.LimitToSkill não abstraído");
            set => throw new NotSupportedException("SelectSkill.LimitToSkill não abstraído");
        }
        public string LinkedAttribute
        {
            get => throw new NotSupportedException("SelectSkill.LinkedAttribute não abstraído");
            set => throw new NotSupportedException("SelectSkill.LinkedAttribute não abstraído");
        }
        public int MaximumRating
        {
            get => throw new NotSupportedException("SelectSkill.MaximumRating não abstraído");
            set => throw new NotSupportedException("SelectSkill.MaximumRating não abstraído");
        }
        public int MinimumRating
        {
            get => throw new NotSupportedException("SelectSkill.MinimumRating não abstraído");
            set => throw new NotSupportedException("SelectSkill.MinimumRating não abstraído");
        }
        public string OnlyCategory
        {
            get => throw new NotSupportedException("SelectSkill.OnlyCategory não abstraído");
            set => throw new NotSupportedException("SelectSkill.OnlyCategory não abstraído");
        }
        public string OnlySkillGroup
        {
            get => throw new NotSupportedException("SelectSkill.OnlySkillGroup não abstraído");
            set => throw new NotSupportedException("SelectSkill.OnlySkillGroup não abstraído");
        }
        public string SelectedSkill
        {
            get => throw new NotSupportedException("SelectSkill.SelectedSkill não abstraído");
            set => throw new NotSupportedException("SelectSkill.SelectedSkill não abstraído");
        }
    }

    /// <summary>Stub de SelectSkillGroup. Membros usados pelo domínio: 4.</summary>
    public sealed class SelectSkillGroup : DialogStubBase
    {
        public SelectSkillGroup() { }
        public SelectSkillGroup(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectSkillGroup.Description não abstraído");
            set => throw new NotSupportedException("SelectSkillGroup.Description não abstraído");
        }
        public string ExcludeCategory
        {
            get => throw new NotSupportedException("SelectSkillGroup.ExcludeCategory não abstraído");
            set => throw new NotSupportedException("SelectSkillGroup.ExcludeCategory não abstraído");
        }
        public string OnlyGroup
        {
            get => throw new NotSupportedException("SelectSkillGroup.OnlyGroup não abstraído");
            set => throw new NotSupportedException("SelectSkillGroup.OnlyGroup não abstraído");
        }
        public string SelectedSkillGroup
        {
            get => throw new NotSupportedException("SelectSkillGroup.SelectedSkillGroup não abstraído");
            set => throw new NotSupportedException("SelectSkillGroup.SelectedSkillGroup não abstraído");
        }
    }

    /// <summary>Stub de SelectSpell. Membros usados pelo domínio: 5.</summary>
    public sealed class SelectSpell : DialogStubBase
    {
        public SelectSpell() { }
        public SelectSpell(params object[] args) { }
        public bool AddAgain
        {
            get => throw new NotSupportedException("SelectSpell.AddAgain não abstraído");
            set => throw new NotSupportedException("SelectSpell.AddAgain não abstraído");
        }
        public string ForceSpellName
        {
            get => throw new NotSupportedException("SelectSpell.ForceSpellName não abstraído");
            set => throw new NotSupportedException("SelectSpell.ForceSpellName não abstraído");
        }
        public bool IgnoreRequirements
        {
            get => throw new NotSupportedException("SelectSpell.IgnoreRequirements não abstraído");
            set => throw new NotSupportedException("SelectSpell.IgnoreRequirements não abstraído");
        }
        public string LimitCategory
        {
            get => throw new NotSupportedException("SelectSpell.LimitCategory não abstraído");
            set => throw new NotSupportedException("SelectSpell.LimitCategory não abstraído");
        }
        public string SelectedSpell
        {
            get => throw new NotSupportedException("SelectSpell.SelectedSpell não abstraído");
            set => throw new NotSupportedException("SelectSpell.SelectedSpell não abstraído");
        }
    }

    /// <summary>Stub de SelectSpellCategory. Membros usados pelo domínio: 4.</summary>
    public sealed class SelectSpellCategory : DialogStubBase
    {
        public SelectSpellCategory() { }
        public SelectSpellCategory(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectSpellCategory.Description não abstraído");
            set => throw new NotSupportedException("SelectSpellCategory.Description não abstraído");
        }
        public string OnlyCategory
        {
            get => throw new NotSupportedException("SelectSpellCategory.OnlyCategory não abstraído");
            set => throw new NotSupportedException("SelectSpellCategory.OnlyCategory não abstraído");
        }
        public string SelectedCategory
        {
            get => throw new NotSupportedException("SelectSpellCategory.SelectedCategory não abstraído");
            set => throw new NotSupportedException("SelectSpellCategory.SelectedCategory não abstraído");
        }
        public void SetExcludeCategories(params object[] args) => throw new NotSupportedException("SelectSpellCategory.SetExcludeCategories não abstraído");
    }

    /// <summary>Stub de SelectText. Membros usados pelo domínio: 3.</summary>
    public sealed class SelectText : DialogStubBase
    {
        public SelectText() { }
        public SelectText(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectText.Description não abstraído");
            set => throw new NotSupportedException("SelectText.Description não abstraído");
        }
        public bool PreventXPathErrors
        {
            get => throw new NotSupportedException("SelectText.PreventXPathErrors não abstraído");
            set => throw new NotSupportedException("SelectText.PreventXPathErrors não abstraído");
        }
        public string SelectedValue
        {
            get => throw new NotSupportedException("SelectText.SelectedValue não abstraído");
            set => throw new NotSupportedException("SelectText.SelectedValue não abstraído");
        }
    }

    /// <summary>Stub de SelectWeaponCategory. Membros usados pelo domínio: 4.</summary>
    public sealed class SelectWeaponCategory : DialogStubBase
    {
        public SelectWeaponCategory() { }
        public SelectWeaponCategory(params object[] args) { }
        public string Description
        {
            get => throw new NotSupportedException("SelectWeaponCategory.Description não abstraído");
            set => throw new NotSupportedException("SelectWeaponCategory.Description não abstraído");
        }
        public string OnlyCategory
        {
            get => throw new NotSupportedException("SelectWeaponCategory.OnlyCategory não abstraído");
            set => throw new NotSupportedException("SelectWeaponCategory.OnlyCategory não abstraído");
        }
        public string SelectedCategory
        {
            get => throw new NotSupportedException("SelectWeaponCategory.SelectedCategory não abstraído");
            set => throw new NotSupportedException("SelectWeaponCategory.SelectedCategory não abstraído");
        }
        public string WeaponType
        {
            get => throw new NotSupportedException("SelectWeaponCategory.WeaponType não abstraído");
            set => throw new NotSupportedException("SelectWeaponCategory.WeaponType não abstraído");
        }
    }

}
